name: Webpack Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        run: npm install --legacy-peer-deps

      - name: Install Dependencies
        run: npm install --force

      - name: Build Webpack
        run: npm run build

        
  
  
        
